"""Pytest configuration and fixtures for SchellingChords M0 tests."""
from tests.golden import (
    DIATONIC_CHORDS, OVERLAP_COUNTS, DISTANCES,
    WINDOW_TOTAL_SLOTS, WINDOW_SLOTS, WINDOW_OCCUPIED_INDICES,
    WINDOW_VACANT_INDICES, WINDOW_OCCUPIED_SLOTS, WINDOW_VACANT_SLOTS
)
